modify legit-log

diff --git a/assignment1/legit-log b/assignment1/legit-log
--- a/assignment1/legit-log
+++ b/assignment1/legit-log
@@ -14,8 +14,12 @@ log()
     then
         echo "legit-log: error: no .legit directory containing legit repository exists"
         exit 1
-        
-    elif ! [ "`ls -a $fullpath/$indexdir`" = "" ]
+    elif [ ! -d $fullpath/$indexdir ]
+    then
+        echo 'legit-log: error: your repository does not have any commits yet'
+        exit 1
+    fi
+    if ! [ "`ls -a $fullpath/$indexdir`" = "" ]
     then
         echo 'legit-log: error: your repository does not have any commits yet'
         exit 1
