add show

diff --git a/assignment1/legit-show b/assignment1/legit-show
--- a/assignment1/legit-show
+++ b/assignment1/legit-show
@@ -1,3 +1,29 @@
-#!/bin/dash
+#!/bin/sh
+# written by Wanze Liu
+
+legitdir='.legit'
+sub_legitdir='.git'
+fullpath="$legitdir/$sub_legitdir"
+indexdir="objects"
+
+# Subset 0
+# function 4 log
+# The legit­show should print the contents of the specified file as of the specified commit. If the commit is omitted the contents of the file in the index should be printed.
+
+show()
+{
+    if [ ! -d $fullpath ]
+    then
+        echo "legit-show: error: no .legit directory containing legit repository exists"
+        exit 1
+
+    elif [ ! -d $fullpath/$indexdir ]
+    then
+        echo 'legit-show: error: your repository does not have any commits yet'
+        exit 1
+    fi
 
 
+}
+
+show() $@
