modify legit-show

diff --git a/assignment1/legit-show b/assignment1/legit-show
--- a/assignment1/legit-show
+++ b/assignment1/legit-show
@@ -35,24 +35,28 @@ show()
     filename=`echo $1 | sed "s/.*://"`
     num=`echo $1 | sed "s/:.*//"`
     #aviod invalid input
-    if !( echo "$num" | egrep "^[0-9]+$")>/dev/null
-    then
-        echo "legit-show: error: unknown commit '$num'"
-        exit 1
-    fi
-    if [ ! -d $fullpath/.commit_$num ]
-    then
-        echo "legit-show: error: unknown commit '$num'"
-        exit 1
-    fi
-    if [ ! -f $fullpath/.commit_$num/$filename ]
-    then
-        echo "legit-show: error: '$filename' not found in commit $num"
-        exit 1
-    fi
+   # if !( echo "$num" | egrep "^[0-9]+$")>/dev/null
+   # then
+   #     echo "legit-show: error: unknown commit '$num'"
+   #     exit 1
+   # fi
+   if ![ "$num" == "" ]
+   then 
     
-    cat $fullpath/.commit_$num/$filename 
-
+        if [ ! -d $fullpath/.commit_$num ]
+        then
+             echo "legit-show: error: unknown commit '$num'"
+             exit 1
+        fi
+        if [ ! -f $fullpath/.commit_$num/$filename ]
+        then
+            echo "legit-show: error: '$filename' not found in commit $num"
+            exit 1
+        fi
+        cat $fullpath/.commit_$num/$filename
+    else  
+        cat $fullpath/.commit_$num/$filename 
+   fi 
 
 }
 
